/**
 * Renders the Playwright spec `mst generate` writes: one test per recorded
 * tool call, asserting on its response with MST's matchers.
 */

/** One recorded tool call and what its test asserts. */
export interface ToolCheck {
  /** The test's title. */
  id: string;
  description?: string;
  toolName: string;
  args: Record<string, unknown>;
  /** Text the response must contain (toContainToolText). */
  containsText?: string[];
  /** Patterns the response must match (toMatchToolPattern). */
  matchesPattern?: string[];
  /** The exact result the call must return (toMatchToolResponse). */
  response?: unknown;
  /** Compare the response with a saved snapshot named after the test. */
  snapshot?: boolean;
}

/** New tests go above this line when `mst generate` adds to a spec. */
export const GENERATED_TESTS_END =
  '// mst generate adds new tests above this line.';

const IMPORT =
  "import { test, expect } from '@gleanwork/mcp-server-tester/fixtures/mcp';";

function literal(value: unknown): string {
  return JSON.stringify(value);
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line ? pad + line : line))
    .join('\n');
}

/** One `test()` block for a recorded call. */
function renderToolCheck(check: ToolCheck): string {
  const lines: string[] = [];
  if (check.description) lines.push(`// ${check.description}`);
  lines.push(`test(${literal(check.id)}, async ({ mcp }) => {`);
  lines.push(
    `  const result = await mcp.callTool(${literal(check.toolName)}, ${literal(check.args)});`
  );
  lines.push('  expect(result).not.toBeToolError();');
  if (check.containsText?.length)
    lines.push(
      `  expect(result).toContainToolText(${literal(check.containsText)});`
    );
  for (const pattern of check.matchesPattern ?? [])
    lines.push(
      `  expect(result).toMatchToolPattern(new RegExp(${literal(pattern)}));`
    );
  if (check.response !== undefined)
    lines.push(
      `  expect(result).toMatchToolResponse(${JSON.stringify(check.response, null, 2).replace(/\n/g, '\n  ')});`
    );
  if (check.snapshot)
    lines.push(
      `  await expect(result).toMatchToolSnapshot(${literal(check.id)});`
    );
  lines.push('});');
  return lines.join('\n');
}

function renderChecks(checks: readonly ToolCheck[]): string {
  return checks.map((check) => indent(renderToolCheck(check), 2)).join('\n\n');
}

/** A new spec: a `describe` named `name`, holding a test per check. */
export function renderToolTestSpec(
  name: string,
  checks: readonly ToolCheck[]
): string {
  const body = checks.length > 0 ? `${renderChecks(checks)}\n\n` : '';
  return `${IMPORT}

// Generated by \`mst generate\`: each test calls one tool and asserts on its
// response. Edit the tests freely; keep the marker line to add more.
test.describe(${literal(name)}, () => {
${body}  ${GENERATED_TESTS_END}
});
`;
}

/** Whether `mst generate` can add tests to this spec. */
export function canAppendToolChecks(source: string): boolean {
  return source.includes(GENERATED_TESTS_END);
}

/** `source` with `checks` added above the generator's marker line. */
export function appendToolChecks(
  source: string,
  checks: readonly ToolCheck[]
): string {
  const at = source.lastIndexOf(GENERATED_TESTS_END);
  if (at < 0)
    throw new Error(
      `The spec has no "${GENERATED_TESTS_END}" line, so mst generate can't add tests to it. Choose a new --output file.`
    );
  if (checks.length === 0) return source;
  const lineStart = source.lastIndexOf('\n', at) + 1;
  return `${source.slice(0, lineStart)}${renderChecks(checks)}\n\n${source.slice(lineStart)}`;
}
